### ISSUE TITLE
[BUG]: TestService: ClientTell Error

### ISSUE THREAD

**Issue by Z0SC** [typical-developers/oaklands-feedback#274]
### Roblox Username

Z3SC

### What version did this issue occur in?

1.51.1

### Describe the issue in detail.

Accidentally Unboxed a structure I was purchasing, upon attempting to put the structure back into the box it errored and I am now stuck in placement mode.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/161517180/2796b80e-14ec-4e31-adbd-0ef336dc2039)
![image](https://github.com/typical-developers/oaklands-feedback/assets/161517180/700855e8-0f1c-411e-b585-22986e5a5cdf)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Z0SC** [comment]
Note: I was able to exit the building mode by unboxing the structure again, this time it actually allowed me to exit without error.

**Comment by Z0SC** [comment]
I am having even more issues related to this ClientTell :(
![image](https://github.com/typical-developers/oaklands-feedback/assets/161517180/9f07442b-4615-4941-92f2-533053a1eb10)
![image](https://github.com/typical-developers/oaklands-feedback/assets/161517180/71b25eb1-4103-4b32-a31d-2a412ea9c14e)

**Comment by HooferDevelops** [comment]
Most of these should be fixed when we revamp the building menu, unsure why this is happening.

**Comment by Z0SC** [comment]
Yeah I rejoined because I thought it was a 1 off issue of something not replicating in time but no, I am still getting issues.
