### ISSUE TITLE
[BUG]: Player's head position

### ISSUE THREAD

**Issue by CaydinDev8434** [typical-developers/oaklands-feedback#372]
### Roblox Username

RedScripting

### What version did this issue occur in?

1.54.3

### Describe the issue in detail.

This is something that has to be fixed, The character's head keeps changing the position and it's very weird hope you can fix this, This occurred even before this version, The head keeps going down into the stomach and doesn't make sense please fix this!

### Provide some images / videos of the issue in action.

https://media.discordapp.net/attachments/1063479705723998359/1230672014709231697/image.png?ex=66342ba1&is=6621b6a1&hm=dc06366be20986382b219b8585af2369ea1f6ee98faa7a55b2f5678bc5197210&=&format=webp&quality=lossless&width=410&height=350

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
I believe I have fixed this.

**Comment by Marzky819** [comment]
Not Fixed It Still Happens
![Screenshot 2024-04-19 164907](https://github.com/typical-developers/oaklands-feedback/assets/151167593/34e3e7ec-1663-4cec-b9de-70fcbf324887)

**Comment by CaydinDev8434** [comment]
Alright

**Comment by Marzky819** [comment]
it has something to do with swimming up and in water
