### ISSUE TITLE
[BUG]: Drag multi-select occasionally breaks during use [1.64.0]

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#828]
### Roblox Username

tupisupi

### What version did this issue occur in?

1.64.0

### Describe the issue in detail.

Use drag multi select until it breaks, don't really know how else to describe it, see images for F9 logs. Has happened to me three times so far, should be fairly easy to replicate unless its somehow related to me or my plot.

### Provide some images / videos of the issue in action.

![RobloxPlayerBeta_UteUwfltnF](https://github.com/user-attachments/assets/bc5ecf0d-3b0c-47ea-8151-c6c39423eb5e)

![RobloxPlayerBeta_JRvDeGewCY](https://github.com/user-attachments/assets/cc90ca69-c245-46f3-93ea-7ee6c8e7fb95)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
I fixed these errors, unsure if this will fix the problem.

**Comment by BluJay2** [comment]
I am still having these problems
Hasn't happened in a long time, but someone joined and it just stopped working

**Comment by BluJay2** [comment]
![image](https://github.com/user-attachments/assets/3ed7ad85-7778-4c0e-8044-26a2e63216d7)
I have 13 of these same messages (including ones in picture)
